version: '3'
services:
  nginx: 
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: emiscode/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - prod-network
    depends_on:
      - "node1"
      - "node2"
      - "node3"

  mongodb:
    image: mongo
    container_name: my-mongo
    networks:
      - prod-network

  node1: 
    build:
      dockerfile: ./docker/app-node.dockerfile
      context: .
    image: emiscode/books-store
    container_name: books-store-1
    ports:
      - "3000"
    networks:
      - prod-network
    depends_on:
      - "mongodb"

  node2: 
    build:
      dockerfile: ./docker/app-node.dockerfile
      context: .
    image: emiscode/books-store
    container_name: books-store-2
    ports:
      - "3000"
    networks:
      - prod-network
    depends_on:
      - "mongodb"
  
  node3: 
    build:
      dockerfile: ./docker/app-node.dockerfile
      context: .
    image: emiscode/books-store
    container_name: books-store-3
    ports:
      - "3000"
    networks:
      - prod-network
    depends_on:
      - "mongodb"

networks:
  prod-network:
    driver: bridge